# Bỏ qua kiểm tra quyền file (Cần thiết khi chạy trên Windows Docker)
setup.strict.perms: false

filebeat.inputs:
  # Đọc từ file log của Spring Boot app
  - type: log
    enabled: true
    paths:
      - /usr/share/cinema/logs/*.log
    fields:
      service: cinema-booking
      environment: dev
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

  # Đọc log từ Docker containers (Vô hiệu hóa để tránh lỗi trên Windows)
  - type: container
    enabled: false
    paths:
      - /var/lib/docker/containers/*/*.log

output.logstash:
  hosts: ["logstash:5044"]
  worker: 1
  backoff.max: 15s

# Logging của chính Filebeat
logging.level: warning
logging.to_files: false
