spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD:}
      timeout: 5000
      ssl:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 86400

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

server:
  port: ${PORT:8081}
  address: 0.0.0.0

vnpay:
  tmn-code: ${TMN_CODE}
  hash-secret: ${TMN_KEY}
  payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: ${PROD_URL}/api/v1/payments/vnpay/return
  ipn-url: ${PROD_URL}/api/v1/payments/vnpay/ipn
  app-return-url: cinema-booking://payment-return
  version: "2.1.0"
  command: pay
  currency-code: VND
  locale: vn

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO

app:
  frontend-url: ${PROD_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false
    redis:
      enabled: false

