package org.example.cinemaBooking.Exception;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE, makeFinal = true)
public enum ErrorCode {
    UNCAUGHT_EXCEPTION(9999, "Uncaught exception", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_EXISTED(1001, "User already existed", HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND(1002, "User not found", HttpStatus.NOT_FOUND),
    USERNAME_EXISTED(1003, "Username already existed", HttpStatus.BAD_REQUEST),
    USERNAME_INVALID(1004, "Username is invalid", HttpStatus.BAD_REQUEST),
    PASSWORD_INVALID(1005, "Password is invalid", HttpStatus.BAD_REQUEST),
    WRONG_PASSWORD(1006, "Wrong password", HttpStatus.BAD_REQUEST),
    EMAIL_EXISTED(1007, "Email already existed", HttpStatus.BAD_REQUEST),
    EMAIL_INVALID(1008, "Email is invalid", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1009, "Unauthenticated", HttpStatus.UNAUTHORIZED),
    ROLE_INVALID(1010, "Role is invalid", HttpStatus.BAD_REQUEST),
    UNAUTHORIZED(1011, "U dont have permission", HttpStatus.FORBIDDEN),
    CATEGORY_NOT_FOUND(1012, "Category not found", HttpStatus.NOT_FOUND),
    PRODUCT_NOT_FOUND(1013, "Product not found", HttpStatus.NOT_FOUND),
    TABLE_NOT_FOUND(1014, "Table not found", HttpStatus.NOT_FOUND),
    ORDER_NOT_FOUND(1015, "Order not found", HttpStatus.NOT_FOUND),
    PASSWORD_CONFIRM_NOT_MATCH(1016, "Password confirm not match", HttpStatus.BAD_REQUEST),
    PASSWORD_SAME_AS_OLD(1017, "New password must be different from old password", HttpStatus.BAD_REQUEST),
    INVALID_RESET_TOKEN(1018, "Invalid or expired reset token", HttpStatus.BAD_REQUEST),
    EMAIL_REQUIRED(1019, "Email is required", HttpStatus.BAD_REQUEST),
    TOKEN_REQUIRED(1020, "Reset token is required", HttpStatus.BAD_REQUEST),
    PASSWORD_REQUIRED(1021, "New password is required", HttpStatus.BAD_REQUEST),
    CONFIRM_PASSWORD_REQUIRED(1022, "Confirm password is required", HttpStatus.BAD_REQUEST),
    USERNAME_REQUIRED(1023, "Username is required", HttpStatus.BAD_REQUEST),
    FULLNAME_REQUIRED(1024, "Full name is required", HttpStatus.BAD_REQUEST),
    PHONE_REQUIRED(1025, "Phone number is required", HttpStatus.BAD_REQUEST),
    PASSWORD_TOO_SHORT(1026, "Password must be at least 8 characters", HttpStatus.BAD_REQUEST),
    OLD_PASSWORD_REQUIRED(1027, "Old password is required", HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_REQUIRED(1028, "New password is required", HttpStatus.BAD_REQUEST),
    IMAGE_URL_NOT_BLANK(1029, "Image URL must not be blank", HttpStatus.BAD_REQUEST),
    ROLE_REQUIRED(1030, "Role is required", HttpStatus.BAD_REQUEST),
    ROLE_NOT_EXIST(1031, "Role does not exist", HttpStatus.BAD_REQUEST),
    INVALID_AGE_RATING(1032, "ageRating must in P|C13|C16|C18", HttpStatus.BAD_REQUEST),
    TITLE_REQUIRED(1033, "Title is required", HttpStatus.BAD_REQUEST),
    SLUG_REQUIRED(1034, "Slug is required", HttpStatus.BAD_REQUEST),
    DURATION_REQUIRED(1035, "Duration is required", HttpStatus.BAD_REQUEST),
    RELEASE_DATE_REQUIRED(1036, "Release date is required", HttpStatus.BAD_REQUEST),
    LANGUAGE_REQUIRED(1037, "Language is required", HttpStatus.BAD_REQUEST),
    POSTER_URL_REQUIRED(1038, "Poster URL is required", HttpStatus.BAD_REQUEST),
    TRAILER_URL_REQUIRED(1039, "Trailer URL is required", HttpStatus.BAD_REQUEST),
    CATEGORIES_REQUIRED(1040, "Categories is required", HttpStatus.BAD_REQUEST),
    MOVIE_NOT_FOUND(1042, "Movie not found", HttpStatus.NOT_FOUND),
    MOVIE_STATUS_INVALID(1043, "Movie status must in COMING_SOON|NOW_SHOWING|ENDED", HttpStatus.BAD_REQUEST),
    MOVIE_IMAGE_NOT_FOUND(1044, "Movie image not found", HttpStatus.NOT_FOUND),
    PEOPLE_NOT_FOUND(1045, "People not found", HttpStatus.NOT_FOUND),
    PEOPLE_IS_IN_MOVIE(1046, "People is in movie", HttpStatus.BAD_REQUEST),
    MOVIE_PEOPLE_NOT_FOUND(1047, "Movie people not found", HttpStatus.NOT_FOUND),
    IMAGE_URL_REQUIRED(1048, "Image URL is required", HttpStatus.BAD_REQUEST),
    IMAGE_URL_LIST_REQUIRED(1049, "Image URL list is required", HttpStatus.BAD_REQUEST),
    REVIEW_ALREADY_EXISTS(1050, "Review already exists for this user and movie", HttpStatus.BAD_REQUEST),
    REVIEW_NOT_FOUND(1051, "Review not found", HttpStatus.NOT_FOUND),
    CONCURRENT_UPDATE(1052,"concurrent update",HttpStatus.BAD_REQUEST ),
    CATEGORY_ALREADY_EXISTS(1053,"category already exists" , HttpStatus.BAD_REQUEST ),
    MOVIE_SLUG_ALREADY_EXISTS(1054, "movie slug exists", HttpStatus.BAD_REQUEST),
    INVALID_REQUEST(1055, "Invalid request", HttpStatus.BAD_REQUEST),
    MOVIE_CANNOT_HAVE_MULTIPLE_DIRECTORS(1056, "Movie cannot have multiple directors", HttpStatus.BAD_REQUEST),
    MOVIE_ALREADY_HAS_DIRECTOR(1057,"Movie has already a director" , HttpStatus.BAD_REQUEST ),
    INVALID_MOVIE_ROLE(1058, "movie role invalid", HttpStatus.BAD_REQUEST ),
    DUPLICATE_PEOPLE_IN_REQUEST(1059, "duplicate people in request" , HttpStatus.BAD_REQUEST ),
    NAME_REQUIRED(1060, "Name is required", HttpStatus.BAD_REQUEST),
    PRICE_REQUIRED(1061, "Price is required", HttpStatus.BAD_REQUEST),
    PRICE_INVALID(1062, "Price must be greater than 0", HttpStatus.BAD_REQUEST),
    PRODUCT_ALREADY_EXISTS(1063, "Product already exists", HttpStatus.BAD_REQUEST),
    ROOM_NOT_FOUND(1064, "Room not found", HttpStatus.NOT_FOUND),
    ROOM_ALREADY_EXISTS(1065, "Room already exists", HttpStatus.BAD_REQUEST),
    ROOM_NAME_REQUIRED(1066, "Room name is required", HttpStatus.BAD_REQUEST),
    TOTAL_SEATS_REQUIRED(1067, "Total seats is required", HttpStatus.BAD_REQUEST),
    TOTAL_SEATS_INVALID(1068, "Total seats must be greater than 0", HttpStatus.BAD_REQUEST),
    ROOM_TYPE_INVALID(1069, "Room type is in TWO_D, THREE_D, IMAX", HttpStatus.BAD_REQUEST),
    CINEMA_NOT_FOUND(1070, "Cinema not found", HttpStatus.NOT_FOUND),
    ROOM_ALREADY_INACTIVE(1071, "Room already inactive", HttpStatus.BAD_REQUEST),
    ROOM_ALREADY_DELETED(1072, "Room already deleted", HttpStatus.BAD_REQUEST),
    ROOM_HAS_SCHEDULE(1073, "Room has schedule and cannot be deleted", HttpStatus.BAD_REQUEST),
    CINEMA_ALREADY_EXISTS(1074, "Cinema already exists", HttpStatus.BAD_REQUEST),
    CINEMA_ALREADY_INACTIVE(1075, "Cinema already inactive", HttpStatus.BAD_REQUEST),
    QUANTITY_MIN_VALUE(1076, "Quantity must be at least 1", HttpStatus.BAD_REQUEST),
    PRODUCT_ID_REQUIRED(1077, "Product ID is required", HttpStatus.BAD_REQUEST),
    ITEMS_REQUIRED(1078, "Items is required", HttpStatus.BAD_REQUEST),
    COMBO_ALREADY_EXISTS(1079, "Combo already exists", HttpStatus.BAD_REQUEST),
    COMBO_NOT_FOUND(1080, "Combo not found", HttpStatus.NOT_FOUND),
    DUPLICATE_PRODUCT_IN_COMBO(1081, "Duplicate product in combo", HttpStatus.BAD_REQUEST),
    PRICE_INVALID_FORMAT(1082, "Price must be a valid number", HttpStatus.BAD_REQUEST),
    CODE_REQUIRED(1083, "Code is required", HttpStatus.BAD_REQUEST),
    CODE_TOO_LONG(1084, "Code must be at most 50 characters", HttpStatus.BAD_REQUEST),
    NAME_TOO_LONG(1085, "Name must be at most 50 characters", HttpStatus.BAD_REQUEST),
    DESCRIPTION_TOO_LONG(1086, "Description must be at most 1000 characters", HttpStatus.BAD_REQUEST),
    DISCOUNT_TYPE_REQUIRED(1087, "Discount type is required", HttpStatus.BAD_REQUEST),
    DISCOUNT_VALUE_REQUIRED(1088, "Discount value is required", HttpStatus.BAD_REQUEST),
    DISCOUNT_VALUE_INVALID(1089, "Discount value must be greater than 0", HttpStatus.BAD_REQUEST),
    DISCOUNT_VALUE_FORMAT_INVALID(1090, "Discount value must be a valid number", HttpStatus.BAD_REQUEST),
    MIN_ORDER_VALUE_INVALID(1091, "Min order value must be greater than or equal to 0", HttpStatus.BAD_REQUEST),
    MIN_ORDER_VALUE_FORMAT_INVALID(1092, "Min order value must be a valid number", HttpStatus.BAD_REQUEST),
    MAX_DISCOUNT_INVALID(1093, "Max discount must be greater than or equal to 0", HttpStatus.BAD_REQUEST),
    MAX_DISCOUNT_FORMAT_INVALID(1094, "Max discount must be a valid number", HttpStatus.BAD_REQUEST),
    QUANTITY_INVALID(1095, "Quantity must be at least 1", HttpStatus.BAD_REQUEST),
    START_DATE_REQUIRED(1096, "Start date is required", HttpStatus.BAD_REQUEST),
    END_DATE_REQUIRED(1097, "End date is required", HttpStatus.BAD_REQUEST),
    MAX_USAGE_PER_USER_REQUIRED(1098, "Max usage per user is required", HttpStatus.BAD_REQUEST),
    MAX_USAGE_PER_USER_INVALID(1099, "Max usage per user must be at least 1", HttpStatus.BAD_REQUEST),
    PROMOTION_NOT_FOUND(1100, "Promotion not found", HttpStatus.NOT_FOUND),
    PROMOTION_ALREADY_EXISTS(1101, "Promotion already exists", HttpStatus.BAD_REQUEST),
    START_DATE_INVALID(1102, "Start date must not be in the past", HttpStatus.BAD_REQUEST),
    END_DATE_INVALID(1103, "End date must be after start date", HttpStatus.BAD_REQUEST),
    INVALID_DATE_RANGE(1104, "Start date must be before end date", HttpStatus.BAD_REQUEST),
    MAX_DISCOUNT_INVALID_FOR_PERCENTAGE(1105, "Max discount must be greater than or equal to discount value for percentage type", HttpStatus.BAD_REQUEST),
    INVALID_DISCOUNT_VALUE_FOR_PERCENTAGE(1106, "Discount value must be less than or equal to 100 for percentage type", HttpStatus.BAD_REQUEST),
    PROMOTION_ALREADY_DELETED(1107, "Promotion already deleted", HttpStatus.BAD_REQUEST),
    PROMOTION_EXPIRED(1108, "Promotion expired", HttpStatus.BAD_REQUEST),
    PROMOTION_NOT_STARTED(1109, "Promotion not started", HttpStatus.BAD_REQUEST),
    PROMOTION_OUT_OF_STOCK(1110, "Promotion out of stock", HttpStatus.BAD_REQUEST),
    PROMOTION_USAGE_LIMIT_EXCEEDED(1111, "Promotion usage limit exceeded", HttpStatus.BAD_REQUEST),
    QUANTITY_LESS_THAN_USED(1112, "Quantity must be greater than or equal to used quantity", HttpStatus.BAD_REQUEST),
    MAX_DISCOUNT_NOT_ALLOWED(1113, "Max discount is not allowed for fixed discount type", HttpStatus.BAD_REQUEST),
    SHOWTIME_NOT_FOUND(1114, "Showtime not found", HttpStatus.NOT_FOUND),
    SHOWTIME_CONFLICT(1115, "Room already has a showtime overlapping", HttpStatus.BAD_REQUEST),
    SHOWTIME_STATE_INVALID(1116, "Showtime status must be SCHEDULED to update", HttpStatus.BAD_REQUEST),
    MOVIE_ID_REQUIRED(1117, "Movie ID is required", HttpStatus.BAD_REQUEST),
    ROOM_ID_REQUIRED(1118, "Room ID is required", HttpStatus.BAD_REQUEST),
    START_TIME_REQUIRED(1119, "Start time is required", HttpStatus.BAD_REQUEST),
    BASE_PRICE_REQUIRED(1120, "Base price is required", HttpStatus.BAD_REQUEST),
    START_TIME_MUST_BE_FUTURE(1121, "Start time must be in the future", HttpStatus.BAD_REQUEST),
    BASE_PRICE_MUST_BE_POSITIVE(1122, "Base price must be greater than 0", HttpStatus.BAD_REQUEST),
    BASE_PRICE_INVALID_FORMAT(1123, "Base price must be a valid number with up to 8 digits and 2 decimal places", HttpStatus.BAD_REQUEST),
    SEAT_NOT_FOUND(1124, "Seat not found", HttpStatus.NOT_FOUND),
    SEAT_ALREADY_LOCKED(1125, "Seat already locked", HttpStatus.BAD_REQUEST),
    SEAT_ALREADY_BOOKED(1126, "Seat already booked", HttpStatus.BAD_REQUEST),
    SEAT_NOT_LOCKED(1127, "Seat not locked", HttpStatus.BAD_REQUEST),
    SEAT_LOCK_FORBIDDEN(1128, "You can only release your own locked seats", HttpStatus.FORBIDDEN),
    SEAT_LOCK_MISMATCH(1129, "Some seats are not locked by you", HttpStatus.BAD_REQUEST),
    BOOKING_NOT_FOUND( 1130, "Booking not found", HttpStatus.NOT_FOUND),
    BOOKING_STATUS_INVALID(1131, "Booking status must be PENDING, CONFIRMED, CANCELLED or EXPIRED", HttpStatus.BAD_REQUEST),
    BOOKING_EXPIRED(1132, "Booking expired", HttpStatus.BAD_REQUEST),
    BOOKING_ALREADY_CONFIRMED(1133, "Booking already confirmed", HttpStatus.BAD_REQUEST),
    PAYMENT_NOT_FOUND(1134, "Payment not found", HttpStatus.NOT_FOUND),
    PAYMENT_STATE_INVALID(1135, "Payment is not in a valid state for this action", HttpStatus.BAD_REQUEST),
    PAYMENT_INVALID_SIGNATURE(1136, "Payment signature is invalid", HttpStatus.BAD_REQUEST),
    NOTIFICATION_NOT_FOUND(1137, "Notification not found", HttpStatus.NOT_FOUND),
    TICKET_NOT_VALID(1138, "Ticket is not valid for check-in", HttpStatus.BAD_REQUEST),
    SHOWTIME_NOT_ONGOING(1139, "Showtime is not ongoing for check-in", HttpStatus.BAD_REQUEST),
    TICKET_NOT_FOUND(1140, "Ticket not found", HttpStatus.NOT_FOUND),
    SEAT_ALREADY_EXISTS(1141, "Seat already exists in the same room with the same row and number", HttpStatus.BAD_REQUEST),
    SEAT_TYPE_NOT_FOUND(1142, "Seat type not found", HttpStatus.NOT_FOUND),
    CINEMA_ID_REQUIRED(1143, "Cinema ID is required", HttpStatus.BAD_REQUEST),
    BOOKING_CANCELLED(1144, "Booking is cancelled", HttpStatus.BAD_REQUEST),
    LANGUAGE_INVALID(1145, "Language must be in ORIGINAL, DUBBED, SUBTITLED", HttpStatus.BAD_REQUEST),
    SHOWTIME_STATUS_INVALID(1146, "Showtime status must be in SCHEDULED, ONGOING, FINISHED, CANCELLED", HttpStatus.BAD_REQUEST),
    SEAT_LOCK_EXPIRED(1147, "Seat lock expired", HttpStatus.BAD_REQUEST),
    FILE_EMPTY(1148, "File is empty", HttpStatus.BAD_REQUEST),
    FILE_TOO_LARGE(1149, "File size must be less than 5MB", HttpStatus.BAD_REQUEST),
    FILE_TYPE_INVALID(1150, "File type must be image/video", HttpStatus.BAD_REQUEST),
    FILE_DELETE_FAILED(1151, "Failed to delete file", HttpStatus.INTERNAL_SERVER_ERROR),
    FILE_UPLOAD_FAILED(1152, "Failed to upload file", HttpStatus.INTERNAL_SERVER_ERROR),
    USER_BANNED(1153, "User is banned", HttpStatus.FORBIDDEN)
    ;


     int code;
     String message;
     HttpStatusCode httpStatusCode;

}
