# logstash/pipeline/logstash.conf
input {
  # Nhận log trực tiếp từ Spring Boot qua TCP (logback LogstashTcpSocketAppender)
  tcp {
    port => 5000
    codec => json_lines
  }

  # Nhận log từ Filebeat (đọc file log)
  beats {
    port => 5044
  }
}

filter {
  # optional: add fields, parse stacktrace, enrich
  mutate {
    add_field => { "[@metadata][index]" => "cinema-logs-%{+YYYY.MM.dd}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}"
    ilm_enabled => false
  }
  stdout { codec => rubydebug }  # useful for debugging
}