# logstash/pipeline/logstash.conf
input {
  # Nhận log trực tiếp từ Spring Boot qua TCP (logback LogstashTcpSocketAppender)
  tcp {
    port => 5000
    codec => json_lines
  }

  # Nhận log từ Filebeat (đọc file log)
  beats {
    port => 5044
  }
}

filter {
  # Nếu log đến từ App (TCP input), đổi tên 'host' thành 'app_host'
  # Nếu log đến từ Filebeat, giữ nguyên 'host' (là một object)
  if ![agent] and [host] {
    mutate {
      rename => { "host" => "app_host" }
    }
  }

  mutate {
    add_field => { "[@metadata][index]" => "cinema-logs-%{+YYYY.MM.dd}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}"
    ilm_enabled => false
  }
  stdout { codec => rubydebug }  # useful for debugging
}